***Numpy*** **and** ***Pandas***

**Numpy**

In [1]:
import numpy as np
import math

In [13]:
# Q1
a = []
for i in range(20):
  x = np.random.randint(10,51)
  a.append(x)
print(a)
print("Mean = " ,np.mean(a))
print("Standard Deviation = ", np.std(a))

[27, 16, 44, 18, 38, 49, 19, 36, 50, 10, 28, 47, 21, 27, 21, 17, 34, 31, 40, 34]
Mean =  30.35
Standard Deviation =  11.598599053333983


In [ ]:
# Q2
x = np.random.rand(6,5)
print(x)
a = np.reshape(x,(5,6))
print(a)
a.ndim


[[0.60188091 0.15780727 0.58092993 0.99351999 0.81642035]
 [0.61044678 0.83528419 0.54035387 0.6845372  0.58049177]
 [0.31256321 0.97215331 0.12543801 0.59273038 0.9127864 ]
 [0.47478186 0.2269403  0.0659024  0.21415479 0.76602051]
 [0.3069288  0.28805189 0.70114147 0.49106454 0.94489009]
 [0.74468891 0.34922431 0.53573274 0.58058899 0.52369375]]
[[0.60188091 0.15780727 0.58092993 0.99351999 0.81642035 0.61044678]
 [0.83528419 0.54035387 0.6845372  0.58049177 0.31256321 0.97215331]
 [0.12543801 0.59273038 0.9127864  0.47478186 0.2269403  0.0659024 ]
 [0.21415479 0.76602051 0.3069288  0.28805189 0.70114147 0.49106454]
 [0.94489009 0.74468891 0.34922431 0.53573274 0.58058899 0.52369375]]


2

In [ ]:
# Q3
x = np.arange(1,26)
print(x.reshape(5,5))

a = x.reshape(5,5)
a[1:4,:3]


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


array([[ 6,  7,  8],
       [11, 12, 13],
       [16, 17, 18]])

In [ ]:
# Q4
a = []
b = []

for i in range(10):
  x = np.random.randint(1,100)
  y = np.random.randint(1,100)
  a.append(x)
  b.append(y)

print(a)
print(b)
z = np.add(a,b)
print(z)
np.multiply(z,2)

[90, 3, 27, 27, 49, 64, 4, 54, 70, 44]
[1, 75, 33, 62, 35, 40, 63, 31, 32, 89]
[ 91  78  60  89  84 104  67  85 102 133]


array([182, 156, 120, 178, 168, 208, 134, 170, 204, 266])

In [ ]:
# Q5
a = np.random.randint(1,11, size = (3,4))
A = np.array(a)
print(A)
B = np.array([1,2,3,4])

print(B)
matrix_sum = A + B
print(matrix_sum)

[[ 6  8  7 10]
 [ 3  8  1  1]
 [ 1 10  5  5]]
[1 2 3 4]
[[ 7 10 10 14]
 [ 4 10  4  5]
 [ 2 12  8  9]]


In [ ]:
# Q6
a = []
for i in range(9):
  x = np.random.randint(1,100)
  a.append(x)
print(a)
z = np.array(a)
y = z.reshape(3,3)
print(y)
b = np.sum(y,axis=1).reshape(3,1)

print(b)
Max_sum_row = np.argmax(b)
print("Row with the max sum is = ",Max_sum_row)
Max_value_in_that_row = np.max(y[Max_sum_row])
print("Max value in that row is = ",Max_value_in_that_row)


[20, 43, 11, 38, 9, 76, 53, 46, 27]
[[20 43 11]
 [38  9 76]
 [53 46 27]]
[[ 74]
 [123]
 [126]]
Row with the max sum is =  2
Max value in that row is =  53


In [ ]:
# Q7
a = np.random.randint(100,size = (2,2))
b = np.random.randint(100,size = (2,2))
A = np.array(a)
B = np.array(b)
print(A)
print(B)
print(np.dot(A,B))

[[68 34]
 [67 68]]
[[75 20]
 [42 85]]
[[6528 4250]
 [7881 7120]]


In [ ]:
# Q8
a = np.random.randint(1,51, size = (6,6))
A = np.array(a)
print(A)
filtered_arr = A[A > 25]
print("Filtered value = ",filtered_arr)


[[21 38 23  1 46 47]
 [40 35 28 38 39 20]
 [47 17 12 29 23 19]
 [49  9 47  5 50 24]
 [ 7 35  8 14 26 18]
 [19 44 48 13  2 47]]
Filtered value =  [38 46 47 40 35 28 38 39 47 29 49 47 50 35 26 44 48 47]


In [ ]:
# Q9
x = np.random.rand(5,5)
print(x)
a = np.median(x,axis = 0)
print("Median along Columns =",a)
b = np.median(x,axis = 1)
print("Median along Rows =",b)
c = np.var(x,axis = 0)
print("Variance along Columns =",c)
d = np.var(x,axis = 1)
print("Variance along Rows =",d)


[[0.97218827 0.70021628 0.16855412 0.34024736 0.38238347]
 [0.68029282 0.04417931 0.96547897 0.94622576 0.37484084]
 [0.90031091 0.18724601 0.9764975  0.65265767 0.76568918]
 [0.34811305 0.64087653 0.60853613 0.92258666 0.77581125]
 [0.6149299  0.59569577 0.85776354 0.31573608 0.2166831 ]]
Median along Columns = [0.68029282 0.59569577 0.85776354 0.65265767 0.38238347]
Median along Rows = [0.38238347 0.68029282 0.76568918 0.64087653 0.59569577]
Variance along Columns = [0.0491221  0.07053232 0.09228781 0.07373734 0.05127641]
Variance along Rows = [0.0822901  0.12390062 0.07719728 0.03652968 0.0525101 ]


In [ ]:
# Q 10
a = np.random.randint(1,11,size = (3,3))
A = np.array(a)
print(A)
S = np.subtract(A,2.1)
print("Subtracted matrix =\n",S)
Sq = np.square(S)
print("Squared matrix =\n",Sq)
Re = np.reciprocal(Sq)
print("Reciprocal matrix =\n",Re)

[[9 9 1]
 [2 2 5]
 [2 6 8]]
Subtracted matrix =
 [[ 6.9  6.9 -1.1]
 [-0.1 -0.1  2.9]
 [-0.1  3.9  5.9]]
Squared matrix =
 [[4.761e+01 4.761e+01 1.210e+00]
 [1.000e-02 1.000e-02 8.410e+00]
 [1.000e-02 1.521e+01 3.481e+01]]
Reciprocal matrix =
 [[2.10039908e-02 2.10039908e-02 8.26446281e-01]
 [1.00000000e+02 1.00000000e+02 1.18906064e-01]
 [1.00000000e+02 6.57462196e-02 2.87273772e-02]]


**Pandas**

In [ ]:
# Q1
import pandas as pd
import math
df = pd.read_csv('/content/sample_data/auto-mpg.csv')
print(df.head(11))
print("Total Rows and columns = ",df.shape)
print(df.describe())


     mpg  cylinders  displacement horsepower  weight  acceleration  \
0   18.0          8         307.0        130    3504          12.0   
1   15.0          8         350.0        165    3693          11.5   
2   18.0          8         318.0        150    3436          11.0   
3   16.0          8         304.0        150    3433          12.0   
4   17.0          8         302.0        140    3449          10.5   
5   15.0          8         429.0        198    4341          10.0   
6   14.0          8         454.0        220    4354           9.0   
7   14.0          8         440.0        215    4312           8.5   
8   14.0          8         455.0        225    4425          10.0   
9   15.0          8         390.0        190    3850           8.5   
10  15.0          8         383.0        170    3563          10.0   

    model year  origin                   car name  
0           70       1  chevrolet chevelle malibu  
1           70       1          buick skylark 320  
2  

In [ ]:
# Q2
cars = df[(df["model year"] == 75) & (df["weight"] < 3000)]
required_cars = cars[["car name", "weight", "mpg"]]
print(required_cars)

              car name  weight   mpg
167     toyota corolla    2171  29.0
168         ford pinto    2639  23.0
169        amc gremlin    2914  20.0
170      pontiac astro    2592  23.0
171      toyota corona    2702  24.0
172  volkswagen dasher    2223  25.0
173         datsun 710    2545  24.0
174         ford pinto    2984  18.0
175  volkswagen rabbit    1937  29.0
177         audi 100ls    2694  23.0
178        peugeot 504    2957  23.0
179        volvo 244dl    2945  22.0
180          saab 99le    2671  25.0
181   honda civic cvcc    1795  33.0


In [ ]:
# Q3
df.isna().sum()
x = df[(df["horsepower"] != "?")]["horsepower"].astype(int).median()
y = df["horsepower"].values
y[y == "?"] = x
df["horsepower"] = y.astype(int)
df["horsepower"]


0      130
1      165
2      150
3      150
4      140
      ... 
393     86
394     52
395     84
396     79
397     82
Name: horsepower, Length: 398, dtype: int64

In [ ]:
# Q4
df["power_to_weight_ratio"] = df["horsepower"] / df["weight"]
print(df["power_to_weight_ratio"])

0      0.037100
1      0.044679
2      0.043655
3      0.043694
4      0.040591
         ...   
393    0.030824
394    0.024413
395    0.036601
396    0.030095
397    0.030147
Name: power_to_weight_ratio, Length: 398, dtype: float64


In [ ]:
# Q5
cars = df.groupby("origin")
cars["mpg"].mean()

origin
1    20.083534
2    27.891429
3    30.450633
Name: mpg, dtype: float64

In [ ]:
# Q6
sorted_df_mpg = df.sort_values(by = "mpg", ascending = False )
sorted_10_cars = sorted_df_mpg.head(10)
print(sorted_10_cars)

      mpg  cylinders  displacement  horsepower  weight  acceleration  \
322  46.6          4          86.0          65    2110          17.9   
329  44.6          4          91.0          67    1850          13.8   
325  44.3          4          90.0          48    2085          21.7   
394  44.0          4          97.0          52    2130          24.6   
326  43.4          4          90.0          48    2335          23.7   
244  43.1          4          90.0          48    1985          21.5   
309  41.5          4          98.0          76    2144          14.7   
330  40.9          4          85.0          93    1835          17.3   
324  40.8          4          85.0          65    2110          19.2   
247  39.4          4          85.0          70    2070          18.6   

     model year  origin                         car name  performance_score  \
322          80       3                        mazda glc           0.395327   
329          80       3              honda civic 

In [ ]:
# Q7
def performance_score(row):
    return row['mpg'] * row['acceleration'] / row['weight']

df['performance_score'] = df.apply(performance_score, axis=1)

print("New Column:")
print(df.head())

New Column:
    mpg  cylinders  displacement  horsepower  weight  acceleration  \
0  18.0          8         307.0         130    3504          12.0   
1  15.0          8         350.0         165    3693          11.5   
2  18.0          8         318.0         150    3436          11.0   
3  16.0          8         304.0         150    3433          12.0   
4  17.0          8         302.0         140    3449          10.5   

   model year  origin                   car name  performance_score  \
0          70       1  chevrolet chevelle malibu           0.061644   
1          70       1          buick skylark 320           0.046710   
2          70       1         plymouth satellite           0.057625   
3          70       1              amc rebel sst           0.055928   
4          70       1                ford torino           0.051754   

   power_to_weight_ratio  
0               0.037100  
1               0.044679  
2               0.043655  
3               0.043694  
4    

In [ ]:
# Q8
New_df = df[["model year", "mpg", "weight", "horsepower"]]
print(New_df.describe())

       model year         mpg       weight  horsepower
count  398.000000  398.000000   398.000000  398.000000
mean    76.010050   23.514573  2970.424623  104.296482
std      3.697627    7.815984   846.841774   38.224809
min     70.000000    9.000000  1613.000000   46.000000
25%     73.000000   17.500000  2223.750000   76.000000
50%     76.000000   23.000000  2803.500000   93.000000
75%     79.000000   29.000000  3608.000000  125.000000
max     82.000000   46.600000  5140.000000  230.000000


In [ ]:
# Q9
high_mpg_cars = df[df["mpg"] > 30][["mpg", "cylinders", "horsepower", "weight"]]
print(high_mpg_cars)
high_mpg_cars.to_csv("high_mpg_cars.csv", index = False)

      mpg  cylinders horsepower  weight
53   31.0          4         65    1773
54   35.0          4         69    1613
129  31.0          4         67    1950
131  32.0          4         65    1836
144  31.0          4         52    1649
..    ...        ...        ...     ...
390  32.0          4         96    2665
391  36.0          4         84    2370
394  44.0          4         52    2130
395  32.0          4         84    2295
397  31.0          4         82    2720

[85 rows x 4 columns]


In [ ]:
# Q10
Q1 = df["mpg"].quantile(0.25)
Q3 = df["mpg"].quantile(0.75)
IQR = Q3 - Q1
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR
outlier_df = df[(df["mpg"] < lower_bound) | (df["mpg"] > upper_bound)][["car name", "mpg", "model year"]]
x = print(outlier_df)


      car name   mpg  model year
322  mazda glc  46.6          80
